apiVersion: apps/v1
kind: Deployment
metadata:
	name: website-frontend-gke
spec:
	replicas: 1
	selector:
		matchLabels:
			app: gcp
	templates:
		metadata:
			labels:
				app: gcp
		spec:
			containers:
			- name: website-frontend-gke
			- image: gcr.io/sit-23t1-cicd-pipeline-b7292e5/website-frontend:latest
			  ports:
			  - containerPorts: 3000
			  env:
			  	- name: PORT
			  		value: "3000"
					